# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VirtualAssistantGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ARVA_VISHTI(object):
    def setupUi(self, ARVA_VISHTI):
        ARVA_VISHTI.setObjectName("ARVA_VISHTI")
        ARVA_VISHTI.resize(1020, 740)
        ARVA_VISHTI.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.centralwidget = QtWidgets.QWidget(ARVA_VISHTI)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(600, 100, 400, 540))
        self.label.setStyleSheet("border-color: rgb(240, 240, 240);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/female_robo-removebg-preview.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 100, 400, 540))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("images/male_robo-removebg-preview flip.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 50, 100, 100))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("background-color: transparent")
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/run_button-removebg-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(70, 70))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(550, 50, 100, 100))
        self.pushButton.setStyleSheet("background-color: transparent")
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/stop-removebg-preview1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(85, 85))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(75, 630, 200, 100))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("images/arva-removebg-preview.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(685, 630, 250, 90))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("images/vishti-removebg-preview (1).png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(850, 20, 100, 40))
        self.textBrowser.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textBrowser.setStyleSheet("background-color: transparent;\n"
"color: black;\n"
"font-size: 20px;\n"
"font-family: \"SketchFlow Print\";\n"
"text-align:right;\n"
"border: none;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(650, 20, 200, 40))
        self.textBrowser_2.setStyleSheet("background-color: transparent;\n"
"color: black;\n"
"font-size: 20px;\n"
"font-family: \"SketchFlow Print\";\n"
"text-align:right;\n"
"border: none;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        ARVA_VISHTI.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ARVA_VISHTI)
        self.statusbar.setObjectName("statusbar")
        ARVA_VISHTI.setStatusBar(self.statusbar)

        self.retranslateUi(ARVA_VISHTI)
        QtCore.QMetaObject.connectSlotsByName(ARVA_VISHTI)

    def retranslateUi(self, ARVA_VISHTI):
        _translate = QtCore.QCoreApplication.translate
        ARVA_VISHTI.setWindowTitle(_translate("ARVA_VISHTI", "ARVA_VISHTI"))
        self.textBrowser.setHtml(_translate("ARVA_VISHTI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SketchFlow Print\'; font-size:20px; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("ARVA_VISHTI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SketchFlow Print\'; font-size:20px; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ARVA_VISHTI = QtWidgets.QMainWindow()
    ui = Ui_ARVA_VISHTI()
    ui.setupUi(ARVA_VISHTI)
    ARVA_VISHTI.show()
    sys.exit(app.exec_())

